### ISSUE TITLE
System audio not getting to SoundPusher

### ISSUE THREAD

**Issue by cmkfilm** [q-p/SoundPusher#19]
Love the app! NooB end user here- I was using SoundPusher with great results for a while, and now I can't seem to get any system/app audio to SP. My receiver shows that it's getting a 5.1 signal over SPDIF when SP is active, I can select it as an audio output, but nothing actually comes out.

I've ensured that my SPDIF device is not used by any other app (including disabling multi output devices in  Audio Midi Setup) I've granted SP permissions in both Microphone and Accessibility in System security prefs. and I have a full install of ffMpeg.

Not sure if this is a bug or if I'm missing something. can anyone guide me here? many thanks!!

**Comment by q-p** [comment]
A few places where things could go wrong:
- Wrong forwarding / input device selected in SoundPusher (it used to be hard-coded to `Loopback Audio` but that device has been renamed to `SoundPusher Audio`). Make sure that only one chain in SoundPusher is active (source of the chain in `SoundPusher` is `SoundPusher Audio -> <YourSPDIFDevice>`. (You can also delete the old `Loopback Audio` device if it's still around in `/Library/Audio/Plug-Ins/HAL/`.)
- Inability of SoundPusher to read from the input device (which needs the microphone permissions). You can try `tccutil reset Microphone` from the Terminal.app to reset permissions, start SoundPusher, start the chain, and it should hopefully prompt again.
- Incorrect system sound output settings so that no-one is outputting any audio to the `SoundPusher Audio` device which is what is getting output to the SPDIF output. While SoundPusher is running you probably want the system default device to be `SoundPusher Audio`. It changes this for you automatically, but only if the previous device was the SPDIF-capable device.

You do not need an FFmpeg install, SoundPusher brings its own embedded version containing what it needs.

**Comment by cmkfilm** [comment]
q-p, Thank you so much for your reply!

Thanks for the clarification about ffmpeg as well. I confirmed Loopback wasn't in the HAL folder, I ran the mic reset in terminal, and triple checked, SP was set as the output device.

I'm ashamed to say it seems like I had _muted_ SP in system preferences! Didn't realize this was possible since it's an output w/o volume control.

Also was surprised that being muted in system settings apparently affected apps with independent audio output configurations such as VLC and Davinci Resolve.

In any case, problem solved ;-) Thanks again for your help and this perfect little app!
