### ISSUE TITLE
Missing "com.apple.security.device.microphone" entitlement for SoundPusher

### ISSUE THREAD

**Issue by bdev36** [q-p/SoundPusher#6]
It seems that on the current release of High Sierra (10.13.5 - 17F77) the `com.apple.security.device.microphone` entitlement is required.

On my computer, and without this entitlement, SoundPusher was not working because many calls to `AudioObjectGetPropertyDataSize` where returning a zero size (A least in `GetNumStreams`).

After adding the entitlement and recompiling the app, everything is OK.

**Comment by q-p** [comment]
You're very much right. It was even (obtusely) mentioned in the [security notes for 10.13.5](https://support.apple.com/en-gb/HT208849) as a bug. I simply hadn't started SoundPusher since the upgrade.

I can also confirm that adding the microphone entitlement fixes it.

Thanks for the report! I'll probably get around to "officially" fixing it over the weekend.

**Comment by bdev36** [comment]
I should thank for SoundPusher.

The least I could do was trying to help a bit.
